### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by frenchiveruti** [step-/nathans-wallpaper#3]
Hello, the program adds a "centre:*" on the file directory that I give to it, making the "wallpaper FILE" command unusable.
![showoff](https://cloud.githubusercontent.com/assets/1095997/23368249/46cec17a-fd1e-11e6-8960-38dfeb7b2ec6.png)

**Comment by step-** [comment]
Hello @frenchiveruti, thanks for your report. Inserting `centre:` before the _file name_ (you wrote _directory_) is a feature, not a mistake. It's been there for a long time. Can you please answer these questions for me?
 1. Are you running this app on  Fatdog64? If so, which version? If not, what Puppy-Linux name and version are you running this app on?
 2. How did you get this app installed on your OS? Please be as precise as possible, as I suspect some installation issue.
 3. Was another Nathan's Wallpaper setter installed in your OS before you installed this one? If so, which version?
 4. After you installed, did you need to manually modify anything? Please be specific.

Can you also open a terminal window,
run `/usr/bin/wallpaper /path/to/your/wallpaper.jpg`,
copy+paste all terminal input+output to a text file,
and attach the text file to your reply here?

Thank you

**Comment by step-** [comment]
@frenchiveruti, I added a command-line option to start a slideshow of an entire directory and its sub-folders, so you don't have to create a playlist file, if you don't want to. Run
```sh
wallpaper -play-dir=/path/to/dir
```
to start a slideshow of the image files in `/path/to/dir`.

**Comment by frenchiveruti** [comment]
Hello, I just wanted to modify the single existing desktop background via console so during startup I can manually set it to scale because of another issue...
I failed because of the "centre" thing, I'm using Tahrpup 6.0.5 and I think is the same "wallpaper" because of the commands that I have available, I didn't really check profusely about the version because I assumed it was the same app as I saw the pictures featuring the same GUI.
I'll give you a more detailed answer when i'm back home.
I just want to use a single file not a play slideshow.
Thanks for the reply.

**Comment by step-** [comment]
Tahrpup's Wallpaper Setter descends from the same original Wallpaper Setter that this fork is based on, but it isn't the same thing. Think siblings. The [README](https://github.com/step-/nathans-wallpaper/blob/master/README.md) file explains this is some detail.

You can't mix and match Tahrpup's Wallpaper Setter with this one, or maybe you can, but probably not without editing some of the scripts on your own. You can try to _replace_ Tahrpup's Wallpaper Setter with this one, by overwriting like-named files, and adding the rest in this package.

This version allows you to set a file and specify it's mode with this syntax:
```
wallpaper MODE:/path/to/wallpaper.jpg   # or any of the supported modes, see README
```
where MODE is one of Centre, Tile, Fit, Scale, Stretch, Distort. If you omit "MODE:" it will default to the default mode that was saved in the configuration file via the GUI.

I'm going to close this issue as resolved. Feel free to re-open it if you need assistance.

**Comment by frenchiveruti** [comment]
Hi @step- , I've finally been able to "reset" my puppy linux, so no interference from other version or anything.
I'm still having the same issue as before, when using any file, the command line seems to take as argument the entire "centre:/file/path.jpg" so it tells me that there's no such file or directory, even though there is a file! And a Directory!.
Is there anyway to "update" the default wallpaper that comes with TahrPup? Compiling from code? How do I "remove" the old wallpaper so I avoid conflicts? 
Thanks.

**Comment by step-** [comment]
@frenchiveruti, look insider directory /root/.cache/wallpaper. One of the files in there lists the current wallpaper path, the one starting with "centre". Delete that file and restart the program.

**Comment by frenchiveruti** [comment]
Ok I'll resort on the forums, thanks again for your help. I wish I could delete the default one and use yours that at least works.
